### ISSUE TITLE
Consider rewriting in Typescript

### ISSUE THREAD

**Issue by cypressious** [foxbenjaminfox/vue-async-computed-decorator#2]
Since the project is really tiny, it appears to be more work to provide the types separately than just rewrite the whole thing in Typescript.

**Comment by foxbenjaminfox** [comment]
You're right, it probably would be a good idea to convert it to Typescript. If you'd like to write a PR that does the conversion I'd be happy to merge it, or otherwise I'll find at some point the time to do it myself.
