### ISSUE TITLE
Reminder to remove IAsyncComputedOptions<TResult>

### ISSUE THREAD

**Issue by firefligher** [foxbenjaminfox/vue-async-computed-decorator#7]
This is just a small reminder to remove the `IAsyncComputedOptions<TResult>` from *src/index.ts* after [this PR](https://github.com/foxbenjaminfox/vue-async-computed/pull/91) (or similar) has been merged and a new artifact of vue-async-computed has been deployed to NPM.

**Comment by foxbenjaminfox** [comment]
Thanks! I've made the change in https://github.com/foxbenjaminfox/vue-async-computed-decorator/commit/95fde981a4fc9ef62e876aff42dca9b7c770a34e.
