### ISSUE TITLE
'AsyncComputed' accepts too few arguments to be used as a decorator here

### ISSUE THREAD

**Issue by bruceauyeung** [foxbenjaminfox/vue-async-computed-decorator#8]
i am using `AsyncComputed` decorator with TypeScript-class-based  Vue component.

TypeScript version: 3.5.3
vscode: 1.42.1
Vue: 2.6.10

If i decorate an `async` method of class using  `@AsyncComputed` expression, an error as the title described occurs in vscode editor:
![image](https://user-images.githubusercontent.com/1210201/75857397-22e40a00-5e31-11ea-9017-ae125628bd80.png)

If i decorate the same method using `@AsyncComputed()` expression, vscode shows no error, but when i run this Vue app , there is an error occurred:
>vue.runtime.esm.js:619 [Vue warn]: Error in nextTick: "TypeError: Cannot read property '$scopedSlots' of undefined"
>vue.runtime.esm.js:1888 TypeError: Cannot read property '$scopedSlots' of undefined
>    at updateChildComponent (vue.runtime.esm.js:4103)
>    at prepatch (vue.runtime.esm.js:3125)
>    at patchVnode (vue.runtime.esm.js:6302)
>    at updateChildren (vue.runtime.esm.js:6187)
>    at patchVnode (vue.runtime.esm.js:6313)
>    at updateChildren (vue.runtime.esm.js:6187)
>    at patchVnode (vue.runtime.esm.js:6313)
>    at VueComponent.patch [as __patch__] (vue.runtime.esm.js:6476)
>    at VueComponent.Vue._update (vue.runtime.esm.js:3942)
>    at VueComponent.updateComponent (vue.runtime.esm.js:4060)

**Comment by mustafakibar** [comment]
You can't use '@AsyncComputed' as it  vetur says in the error message. The cause of the error here may be a poorly managed vue lifecycle or incorrectly use scoped slot. I suggest you review the hit vue document.

**Comment by bruceauyeung** [comment]
@mustafakibar `README.md` uses  '@AsyncComputed'  in the usage example, which seems should be corrected.

**Comment by foxbenjaminfox** [comment]
Indeed, that was a mistake in the documentation. I've corrected it.

**Comment by andrejko** [comment]
@foxbenjaminfox pls correct it on this page also https://www.npmjs.com/package/vue-async-computed-decorator
